"""
grammar.py — Lark Grammar Specification for the Mini-Python Interpreter
========================================================================

This module defines the EBNF-style grammar consumed by Lark's Earley / LALR
parser.  The grammar covers **all** language features within scope:

  • Integer and float literals
  • Character literals (single-quoted, one character)
  • Arithmetic expressions with correct precedence
  • Variable assignment (single global scope)
  • Basic conditional statements (if / elif / else)
  • Comparison and boolean operators
  • A built-in ``print`` statement for output

Design Notes
------------
* The grammar is stored as a plain string constant so that other modules can
  import it without touching the filesystem.
* Operator precedence is encoded structurally (lower rules = lower precedence).
* ``print`` is treated as a *statement*, not a function call, to keep the
  grammar simple and avoid the need for a function-call mechanism.
"""

# ---------------------------------------------------------------------------
# Lark Grammar  (LALR-compatible)
# ---------------------------------------------------------------------------

MINI_PYTHON_GRAMMAR: str = r"""
    // ===================================================================
    // Top-Level Program
    // ===================================================================
    // A program is one or more statements separated by newlines.
    program: (_NL* statement)*  _NL*

    // ===================================================================
    // Statements
    // ===================================================================
    ?statement: assignment
              | if_statement
              | print_statement

    // Variable assignment:  <name> = <expression>
    assignment: NAME "=" expression

    // Print statement:  print(<expression>)
    print_statement: "print" "(" expression ")"

    // If / elif / else block
    if_statement: "if" expression ":" block \
                  elif_clause* \
                  else_clause?

    elif_clause: "elif" expression ":" block
    else_clause: "else" ":" block

    // A block is one or more indented statements.
    // For simplicity we use explicit INDENT / DEDENT tokens generated by
    // Lark's built-in indentation post-processor.
    block: _NL _INDENT (statement _NL)+ _DEDENT

    // ===================================================================
    // Expressions  (precedence: low → high, top → bottom)
    // ===================================================================
    ?expression: or_expr

    ?or_expr: and_expr
            | or_expr "or" and_expr          -> or_op

    ?and_expr: not_expr
             | and_expr "and" not_expr       -> and_op

    ?not_expr: comparison
             | "not" not_expr                -> not_op

    ?comparison: arith_expr
               | comparison COMP_OP arith_expr  -> compare

    COMP_OP: "==" | "!=" | "<=" | ">=" | "<" | ">"

    // Arithmetic ---------------------------------------------------------
    ?arith_expr: term
               | arith_expr "+" term         -> add
               | arith_expr "-" term         -> sub

    ?term: factor
         | term "*" factor                   -> mul
         | term "/" factor                   -> div
         | term "//" factor                  -> floor_div
         | term "%" factor                   -> mod

    ?factor: power
           | "+" factor                      -> unary_pos
           | "-" factor                      -> unary_neg

    ?power: atom
          | atom "**" factor                 -> power

    // Atoms (highest precedence) -----------------------------------------
    ?atom: INT                               -> int_literal
         | FLOAT                             -> float_literal
         | CHAR                              -> char_literal
         | "True"                            -> true_literal
         | "False"                           -> false_literal
         | NAME                              -> variable
         | "(" expression ")"

    // ===================================================================
    // Terminals
    // ===================================================================
    // Character literal: a single character enclosed in single quotes.
    CHAR: "'" /[^'\\]/ "'"

    // Use Lark's built-in terminals for INT, FLOAT, NAME.
    // FLOAT must appear before INT so '3.14' is not tokenised as INT+DOT+INT.

    // ===================================================================
    // Whitespace & Newlines
    // ===================================================================
    // Lark handles INDENT / DEDENT via its postlex indentation processor.
    %import common.INT
    %import common.FLOAT
    %import common.CNAME -> NAME
    %import common.WS_INLINE
    %declare _INDENT _DEDENT

    _NL: /(\r?\n[\t ]*)+/

    // Ignore inline whitespace (spaces & tabs within a line)
    %ignore WS_INLINE
    %ignore /\\[\t ]*\r?\n/   // line continuation
"""
